env_manager: local
python_env:
  python: "3.12"
  dependencies:
    - mlflow
    - scikit-learn
    - pandas
    - numpy
    - joblib
    - google-api-python-client
    - google-auth-oauthlib
    - google-auth-httplib2
