name: Train Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Set up job (otomatis)
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Python 3.12.7
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Check Env
      - name: Check Env
        run: |
          python --version
          pip --version

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Set MLflow Tracking URI
      - name: Set MLflow Tracking URI
        run: |
          export MLFLOW_TRACKING_URI="file:./mlruns"
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI"

      # 6. Run mlflow project
      - name: Run mlflow project
        run: |
          mlflow run . --env-manager local

      # 7. Install Python dependencies (jika ada step tambahan dari Dicoding)
      - name: Install Python dependencies (post-run)
        run: |
          pip install google-api-python-client google-auth-oauthlib google-auth-httplib2

      # 8. Upload to Google Drive
      - name: Upload model to Google Drive
        run: |
          python upload_to_gdrive.py

      # Job selesai
