name: train

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        python-version: "3.10"
        auto-update-conda: false
        auto-activate-base: false

    - name: Install MLflow
      run: |
        pip install mlflow

    - name: Run MLflow Project
      run: |
        mlflow run MLProject

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: mlruns
